package app.revanced.manager.ui.theme

import androidx.compose.ui.graphics.Color

// https://materialkolor.com
// Seed: 005FACFF
// Spec 2025, Expressive

val RVThemePrimaryLight = Color(0xFF0061A7)
val RVThemeOnPrimaryLight = Color(0xFFF7F9FF)
val RVThemePrimaryContainerLight = Color(0xFF59A7FA)
val RVThemeOnPrimaryContainerLight = Color(0xFF002647)
val RVThemeInversePrimaryLight = Color(0xFF59A7FA)
val RVThemeSecondaryLight = Color(0xFF546071)
val RVThemeOnSecondaryLight = Color(0xFFF7F9FF)
val RVThemeSecondaryContainerLight = Color(0xFFD7E3F8)
val RVThemeOnSecondaryContainerLight = Color(0xFF475363)
val RVThemeTertiaryLight = Color(0xFF615984)
val RVThemeOnTertiaryLight = Color(0xFFFCF7FF)
val RVThemeTertiaryContainerLight = Color(0xFFD3C8F9)
val RVThemeOnTertiaryContainerLight = Color(0xFF484068)
val RVThemeBackgroundLight = Color(0xFFF9F9FE)
val RVThemeOnBackgroundLight = Color(0xFF2E333A)
val RVThemeSurfaceLight = Color(0xFFF9F9FE)
val RVThemeOnSurfaceLight = Color(0xFF2E333A)
val RVThemeSurfaceVariantLight = Color(0xFFDFE2EC)
val RVThemeOnSurfaceVariantLight = Color(0xFF5B5F67)
val RVThemeSurfaceTintLight = Color(0xFF0061A7)
val RVThemeInverseSurfaceLight = Color(0xFF0C0E12)
val RVThemeInverseOnSurfaceLight = Color(0xFF9C9DA1)
val RVThemeErrorLight = Color(0xFFA83836)
val RVThemeOnErrorLight = Color(0xFFFFF7F6)
val RVThemeErrorContainerLight = Color(0xFFFA746F)
val RVThemeOnErrorContainerLight = Color(0xFF6E0A12)
val RVThemeOutlineLight = Color(0xFF767B83)
val RVThemeOutlineVariantLight = Color(0xFFAEB2BB)
val RVThemeScrimLight = Color(0xFF000000)
val RVThemeSurfaceBrightLight = Color(0xFFF9F9FE)
val RVThemeSurfaceContainerLight = Color(0xFFEBEEF5)
val RVThemeSurfaceContainerHighLight = Color(0xFFE5E8F0)
val RVThemeSurfaceContainerHighestLight = Color(0xFFDFE2EC)
val RVThemeSurfaceContainerLowLight = Color(0xFFF2F3FA)
val RVThemeSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val RVThemeSurfaceDimLight = Color(0xFFD6DAE3)

val RVThemePrimaryDark = Color(0xFFA0C9FF)
val RVThemeOnPrimaryDark = Color(0xFF004274)
val RVThemePrimaryContainerDark = Color(0xFF1777C7)
val RVThemeOnPrimaryContainerDark = Color(0xFFFFFFFF)
val RVThemeInversePrimaryDark = Color(0xFF0061A7)
val RVThemeSecondaryDark = Color(0xFFBBC7DB)
val RVThemeOnSecondaryDark = Color(0xFF354151)
val RVThemeSecondaryContainerDark = Color(0xFF303C4C)
val RVThemeOnSecondaryContainerDark = Color(0xFFB4C0D4)
val RVThemeTertiaryDark = Color(0xFFE1D8FF)
val RVThemeOnTertiaryDark = Color(0xFF504972)
val RVThemeTertiaryContainerDark = Color(0xFFD3C8F9)
val RVThemeOnTertiaryContainerDark = Color(0xFF484068)
val RVThemeBackgroundDark = Color(0xFF0C0E12)
val RVThemeOnBackgroundDark = Color(0xFFE1E5EF)
val RVThemeSurfaceDark = Color(0xFF0C0E12)
val RVThemeOnSurfaceDark = Color(0xFFE1E5EF)
val RVThemeSurfaceVariantDark = Color(0xFF21262D)
val RVThemeOnSurfaceVariantDark = Color(0xFFA7ABB4)
val RVThemeSurfaceTintDark = Color(0xFFA0C9FF)
val RVThemeInverseSurfaceDark = Color(0xFFF9F9FE)
val RVThemeInverseOnSurfaceDark = Color(0xFF535559)
val RVThemeErrorDark = Color(0xFFFA746F)
val RVThemeOnErrorDark = Color(0xFF490006)
val RVThemeErrorContainerDark = Color(0xFF871F21)
val RVThemeOnErrorContainerDark = Color(0xFFFF9993)
val RVThemeOutlineDark = Color(0xFF71767E)
val RVThemeOutlineVariantDark = Color(0xFF434850)
val RVThemeScrimDark = Color(0xFF000000)
val RVThemeSurfaceBrightDark = Color(0xFF282C34)
val RVThemeSurfaceContainerDark = Color(0xFF161A1F)
val RVThemeSurfaceContainerHighDark = Color(0xFF1C2026)
val RVThemeSurfaceContainerHighestDark = Color(0xFF21262D)
val RVThemeSurfaceContainerLowDark = Color(0xFF101418)
val RVThemeSurfaceContainerLowestDark = Color(0xFF000000)
val RVThemeSurfaceDimDark = Color(0xFF0C0E12)

val RVThemePrimaryFixed = Color(0xFF59A7FA)
val RVThemePrimaryFixedDim = Color(0xFF4A9AEB)
val RVThemeOnPrimaryFixed = Color(0xFF000001)
val RVThemeOnPrimaryFixedVariant = Color(0xFF003056)
val RVThemeSecondaryFixed = Color(0xFFD7E3F8)
val RVThemeSecondaryFixedDim = Color(0xFFC9D5E9)
val RVThemeOnSecondaryFixed = Color(0xFF344050)
val RVThemeOnSecondaryFixedVariant = Color(0xFF505C6D)
val RVThemeTertiaryFixed = Color(0xFFD3C8F9)
val RVThemeTertiaryFixedDim = Color(0xFFC5BBEB)
val RVThemeOnTertiaryFixed = Color(0xFF342D54)
val RVThemeOnTertiaryFixedVariant = Color(0xFF514972)
