project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

preserve_hierarchy: false
files:
    - source: /assets/i18n/en.i18n.json
      translation: /assets/i18n/%locale_with_underscore%.i18n.json
      skip_untranslated_strings: true
