name: 🐞 Bug report
description: Report a very clearly broken issue.
title: 'bug: <title>'
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Manager bug report

        Important to note that your issue may have already been reported before. Please check for existing issues [here](https://github.com/revanced/revanced-manager/labels/bug).

  - type: dropdown
    attributes:
      label: Type
      options:
        - Error while running the manager
        - Error at runtime
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Add the steps to reproduce this bug including your environment.
      placeholder: Step 1. Download some files. Step 2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Android version
      description: Android version used.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Manager version
      description: Manager version used.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Target package name
      description: App you tried to patch.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Target package version.
      description: Version of the app you tried to patch.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation type
      options:
        - Non-root
        - Root
    validations:
      required: true
  - type: textarea
    attributes:
      label: Patches selected.
      description: Patches you selected for the app.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device logs (exported using Manager settings).
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I filled out all of the requested information in this issue properly.
          required: true
        - label: The issue is related solely to the ReVanced Manager
          required: true
