body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <picture>
            <source
              width="256px"
              media="(prefers-color-scheme: dark)"
              srcset="https://raw.githubusercontent.com/revanced/revanced-manager/main/assets/revanced-headline/revanced-headline-vertical-dark.svg"
            >
            <img 
              width="256px"
              src="https://raw.githubusercontent.com/revanced/revanced-manager/main/assets/revanced-headline/revanced-headline-vertical-light.svg"
            >
          </picture>
          <br>
          <a href="https://revanced.app/">
             <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/revanced/revanced-manager/main/assets/revanced-logo/revanced-logo.svg" />
                 <img height="24px" src="https://raw.githubusercontent.com/revanced/revanced-manager/main/assets/revanced-logo/revanced-logo.svg" />
             </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://github.com/ReVanced">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://i.ibb.co/dMMmCrW/Git-Hub-Mark.png" />
                   <img height="24px" src="https://i.ibb.co/9wV3HGF/Git-Hub-Mark-Light.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="http://revanced.app/discord">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032563-d4e084b7-244e-4358-af50-26bde6dd4996.png" />
                   <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032563-d4e084b7-244e-4358-af50-26bde6dd4996.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://reddit.com/r/revancedapp">
               <picture>
                   <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032351-9d9d5619-8ef7-470a-9eec-2744ece54553.png" />
                   <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032351-9d9d5619-8ef7-470a-9eec-2744ece54553.png" />
               </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://t.me/app_revanced">
              <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032213-faf25ab8-0bc3-4a94-a730-b524c96df124.png" />
                 <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032213-faf25ab8-0bc3-4a94-a730-b524c96df124.png" />
              </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://x.com/revancedapp">
              <picture>
                 <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/93124920/270180600-7c1b38bf-889b-4d68-bd5e-b9d86f91421a.png">
                 <img height="24px" src="https://user-images.githubusercontent.com/93124920/270108715-d80743fa-b330-4809-b1e6-79fbdc60d09c.png" />
              </picture>
           </a>&nbsp;&nbsp;&nbsp;
           <a href="https://www.youtube.com/@ReVanced">
              <picture>
                 <source height="24px" media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/13122796/178032714-c51c7492-0666-44ac-99c2-f003a695ab50.png" />
                 <img height="24px" src="https://user-images.githubusercontent.com/13122796/178032714-c51c7492-0666-44ac-99c2-f003a695ab50.png" />
             </picture>
           </a>
           <br>
           <br>
           Continuing the legacy of Vanced
        </p>

        # ReVanced Manager feature request

        Before creating a new feature request, please keep the following in mind:

        - **Do not submit a duplicate feature request**: Search for existing feature requests [here](https://github.com/ReVanced/revanced-manager/issues?q=label%3A%22Feature+request%22).
        - **Review the contribution guidelines**: Make sure your feature request adheres to it. You can find the guidelines [here](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms on [revanced.app](https://revanced.app).
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A strong motivation is necessary for a feature request to be considered.
        
        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed feature requests and this is not a duplicate
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
        - label: The feature request is only related to ReVanced Manager.
          required: true
