package app.revanced.manager.util

import android.app.LocaleConfig
import android.content.Context
import android.os.Build
import android.os.LocaleList
import androidx.appcompat.app.AppCompatDelegate
import androidx.core.os.LocaleListCompat
import app.revanced.manager.BuildConfig
import java.util.Locale

object SupportedLocales {
    fun getSupportedLocales(context: Context): List<Locale> {
        var result: List<Locale>? = null
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) result = runCatching {
            LocaleConfig(context).supportedLocales?.toList()
        }.getOrNull()

        return result ?: generated
    }

    fun getCurrentLocale(): Locale? =
        AppCompatDelegate.getApplicationLocales().takeIf { !it.isEmpty }?.get(0)

    fun setLocale(locale: Locale?) = AppCompatDelegate.setApplicationLocales(
        locale?.let { LocaleListCompat.create(it) } ?: LocaleListCompat.getEmptyLocaleList()
    )

    fun getDisplayName(locale: Locale) =
        locale.getDisplayName(locale).replaceFirstChar { it.uppercase(locale) }

    private fun LocaleList.toList() = (0 until size()).map { get(it) }

    private val generated by lazy {
        listOf(
            Locale.ENGLISH,
            *BuildConfig.SUPPORTED_LOCALES.map(Locale::forLanguageTag).toTypedArray()
        )
    }
}
