name: Crowdin

on:
  push:
    branches: [ dev ]
    paths:
      - "app/src/res/values/strings.xml"
      - ".github/workflows/crowdin.yml"
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:


jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Crowdin action
        uses: crowdin/github-action@v2
        with:
          config: ".github/crowdin.yml"
          upload_sources: true
          upload_translations: false
          download_translations: true
          create_pull_request: true
          localization_branch_name: "crowdin_translations"
          pull_request_base_branch_name: "dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
