name: Spotless Check

on:
  pull_request:
    branches:
      - dev

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew spotlessCheck --no-daemon
